name: Python application

# 觸發 workflow 的條件
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # 工作名稱
  build:
    # 運行工作的虛擬機器類型
    runs-on: ubuntu-latest

    steps:
      # 檢出代碼
      - uses: actions/checkout@v2

      # 設置 Python 版本
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      # 安裝依賴
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # 運行 lint 檢查
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      # 運行測試
      - name: Test with pytest
        run: |
          pytest ./tests/test.py
